---
- name: Setup Jenkins Master
  hosts: controller
  become: true
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-11-openjdk-devel.x86_64
      
    jenkins_admin_username: ddelsizov
    jenkins_admin_password: secretpassword
    jenkins_plugins_install_dependencies: true
    jenkins_plugins:
    - ssh
    - docker-plugin
    - git
    - github
    - blueocean

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      
- name: Add Jenkins slave credentials via cli
  hosts: controller
  tasks:
    - name: Run script
      shell: /vagrant/credential.sh
 
- name: Add job
  hosts: controller
  tasks:
    - name: Run script
      shell: /vagrant/createjob.sh