---
- name: Setup Jenkins Master
  hosts: controller
  become: true
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-11-openjdk-devel.x86_64
      
    jenkins_admin_username: ddelsizov
    jenkins_admin_password: secretpassword
    jenkins_plugins_install_dependencies: true
    jenkins_plugins:
    - ssh
    - docker-plugin
    - git
    - github
    - credentials
    
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

- name: Setup Slave role
  hosts: slave
  
  vars:
    master_host: jenkins.home.lab
    master_port: 8090
    master_username: ddelsizov
    master_password: secretpassword
    slave_linux_jenkins_username: jenkins
    slave_linux_jenkins_password: secretpassword
    slave_agent_name: slavehost
    slave_executors_num: 5

  roles:
    - role: lean_delivery.jenkins_slave
    
- name: Install Docker on Slave
  hosts: slave
  roles:
    - geerlingguy.docker

  tasks:
    - name: Add vagrant user to docker group
      user:
        name: 'vagrant'
        groups: docker
        append: yes
        
    - name: Add jenkins user to docker group
      user:
        name: 'jenkins'
        groups: docker
        append: yes
        
