---
- name: Setup Jenkins Master
  hosts: jenkins_master
  become: true
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-11-openjdk-devel.x86_64
      
    jenkins_admin_username: ddelsizov
    jenkins_admin_password: secretpassword
    jenkins_plugins_install_dependencies: true
    jenkins_plugins:
    - ssh
    - docker-plugin
    - git
    - blueocean

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      
- name: Add Jenkins slave and slave1 credentials via cli
  hosts: jenkins_master
  tasks:
    - name: Run script
      shell: /vagrant/credential.sh
 
- name: Add job for slave
  hosts: jenkins_master
  tasks:
    - name: Run script
      shell: /vagrant/createjob.sh

- name: Add job for slave1
  hosts: jenkins_master
  tasks:
    - name: Run Script
      shell: /vagrant/createjob1.sh