---
- name: Install Docker on Slave
  hosts: slave
  roles:
    - geerlingguy.docker

  tasks:
    - name: Add vagrant user to docker group
      user:
        name: 'vagrant'
        groups: docker
        append: yes
        
    - name: Add jenkins user to docker group
      user:
        name: 'jenkins'
        groups: docker
        append: yes
 
- name: Setup Slave role
  hosts: slave
  
  vars:
    master_host: jenkins.home.lab
    master_port: 8080
    master_username: ddelsizov
    master_password: secretpassword
    slave_linux_jenkins_cred_id: ci_slave
    slave_linux_jenkins_username: jenkins
    slave_linux_jenkins_password: secretpassword
    slave_linux_user_group: jenkins
    slave_agent_name: slavehost
    slave_executors_num: 5

  roles:
    - role: lean_delivery.jenkins_slave